packages:
  - "packages/*"
  - "apps/*"
  - "tooling"
allowBuilds:
  esbuild: true
  sharp: true
  "@parcel/watcher": true
  rolldown: true
  wxt: true
  ext-pdf: true
  ext-image: true
  ext-audio: true
