import { chromium } from "@playwright/test";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
const extPath = path.resolve("apps/ext-image/.output/chrome-mv3");
const userDataDir = fs.mkdtempSync(path.join(os.tmpdir(), "ff-heic-"));
const context = await chromium.launchPersistentContext(userDataDir, { channel: "chromium", headless: true, args: [`--disable-extensions-except=${extPath}`, `--load-extension=${extPath}`] });
const p0 = await context.newPage(); await p0.goto("chrome://extensions");
const id = await p0.evaluate(() => document.querySelector("extensions-manager")?.shadowRoot?.querySelector("extensions-item-list")?.shadowRoot?.querySelector("extensions-item")?.getAttribute("id") ?? "");
const page = await context.newPage();
page.on("console", (m) => { if (m.type() === "error" || m.type() === "warning") console.log("[console." + m.type() + "]", m.text().slice(0, 700)); });
page.on("pageerror", (e) => console.log("[pageerror]", e.message.slice(0, 700)));
context.on("weberror", (e) => console.log("[weberror]", e.error().message.slice(0, 700)));
page.on("response", (r) => { if (r.status() >= 400) console.log("[http " + r.status() + "]", r.url()); });
await page.goto(`chrome-extension://${id}/tools.html?tool=heic-to-jpg`);
await page.getByTestId("tool-heic-to-jpg").waitFor();
await page.getByTestId("file-input").setInputFiles([{ name: "photo.heic", mimeType: "image/heic", buffer: fs.readFileSync("tests/fixtures/sample.heic") }]);
await page.getByTestId("run").click();
await page.waitForTimeout(15000);
console.log("download:", await page.getByTestId("download").count(), "error:", await page.getByTestId("error").allTextContents());
console.log("shell:", (await page.getByTestId("tool-heic-to-jpg").innerText()).replace(/\n+/g, " | ").slice(0, 400));
await context.close();
